site_name: CP2025 Docs
site_description: Documentación del proyecto CP2025 (Visual FoxPro 9.0 + foxbin2prg)
site_url: https://yecapp.github.io/CPDOCS/
repo_name: YECAPP/CP2025
theme:
  name: material
  language: es
  features:
    - content.code.copy
    - navigation.instant
    - navigation.sections
    - navigation.tracking
    - search.suggest
    - search.highlight
nav:
  - Inicio: index.md
  - Clases:
      - Factura:
        - Dual: facturacion_dual.md
      - Reportes: reportes.md
  

# markdown_extensions:
#   - admonition
#   - attr_list
#   - def_list
#   - footnotes
#   - tables
#   - toc:
#       permalink: true
#   - pymdownx.details
#   - pymdownx.superfences
#   - pymdownx.highlight
#   - pymdownx.inlinehilite
#   - pymdownx.tabbed
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - tables
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
